<?php

namespace Admin\FrontendUserBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends DocumentRepository
{
}