front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /front

app:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

admin_user:
    resource: "@AdminFrontendUserBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /apii/doc