<?php

namespace ApiBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends DocumentRepository
{
}